# Generated by Django 3.2.3 on 2021-05-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('multiple', 'Multiple'), ('text', 'Text')], default='single', max_length=8),
        ),
    ]
